### ISSUE TITLE
Error determining UniFi unique ID

### ISSUE THREAD

**Issue by cblt2l** [rfpludwick/unifi-phantom-clients-cleanup#7]
I'm running the [Linuxserver.io Unifi controller container](https://docs.linuxserver.io/images/docker-unifi-controller) in docker on a Synology. The controller version is 7.5.174.

I cloned & built the latest from this repo, filled in the config file and when I try to run I get the following:

```
user@mypc ~/P/unifi-phantom-clients-cleanup (main)> ./unifi-phantom-clients-cleanup -verbose
Executing for host https://192.168.50.5:8443
Error determining UniFi unique ID
```

My config file looks like this:

```
---
version: "0.2"
httpLogDirectory: ""
sites:
  - host: "https://192.168.50.5:8443"
    site: "Default"
    username: "username"
    password: "password"
    udmp: false
    validateCertificate: false
```

Any idea what could be wrong? I figured there would be more output from the -verbose flag.
